# **REGRESSION USING KNN**

**The data used in the regression: https://www.kaggle.com/datasets/kuchhbhi/latest-laptop-price-list**

**NOTE: Some of the works are helped by documentations**

In [92]:
import pandas as pd
import numpy as np

In [93]:
df = pd.read_csv('laptop-pricing.csv')
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,Touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,Lenovo,A6-9225,AMD,A6-9225 Processor,10th,4 GB GB,DDR4,0 GB,1024 GB,Windows,...,Missing,0,No,No,24990,32790,23,3.7,63,12
1,Lenovo,Ideapad,AMD,APU Dual,10th,4 GB GB,DDR4,0 GB,512 GB,Windows,...,Missing,0,No,No,19590,21325,8,3.6,1894,256
2,Avita,PURA,AMD,APU Dual,10th,4 GB GB,DDR4,128 GB,0 GB,Windows,...,Missing,0,No,No,19990,27990,28,3.7,1153,159
3,Avita,PURA,AMD,APU Dual,10th,4 GB GB,DDR4,128 GB,0 GB,Windows,...,Missing,0,No,No,21490,27990,23,3.7,1153,159
4,Avita,PURA,AMD,APU Dual,10th,4 GB GB,DDR4,256 GB,0 GB,Windows,...,Missing,0,No,No,24990,33490,25,3.7,1657,234

In [94]:
df.shape

(896, 23)

In [95]:
df.columns

Index(['brand', 'model', 'processor_brand', 'processor_name',
       'processor_gnrtn', 'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit',
       'graphic_card_gb', 'weight', 'display_size', 'warranty', 'Touchscreen',
       'msoffice', 'latest_price', 'old_price', 'discount', 'star_rating',
       'ratings', 'reviews'],
      dtype='object')

**Drop unimportant columns**

In [96]:
df = df.drop('brand', axis = 1)
df = df.drop('model', axis = 1)

**Column renaming**

In [97]:
df.rename(columns = {'Touchscreen': 'touchscreen'}, inplace = True)
df.rename(columns = {'processor_gnrtn': 'processor_generation'}, inplace = True)

**Check the data's condition**

In [98]:
df.shape

(896, 21)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   processor_brand       896 non-null    object
 1   processor_name        896 non-null    object
 2   processor_generation  896 non-null    object
 3   ram_gb                896 non-null    object
 4   ram_type              896 non-null    object
 5   ssd                   896 non-null    object
 6   hdd                   896 non-null    object
 7   os                    896 non-null    object
 8   os_bit                896 non-null    object
 9   graphic_card_gb       896 non-null    int64
 10  weight                896 non-null    object
 11  display_size          896 non-null    object
 12  warranty              896 non-null    int64
 13  touchscreen           896 non-null    object
 14  msoffice              896 non-null    object
 15  latest_price          896 non-null    int64
 16  old_price             896 non-null    int64
 17  discount              896 non-null    int64
 18  star_rating           896 non-null    float64
 19  ratings               896 non-null    int64
 20  reviews               896 non-null    int64
dtypes: float64(1), int64(7), object(13)
memory usage: 147.1+ KB

The reason why both brand and model columns are dropped because it's not ordinal.

**Check for missing values or unique values**

In [100]:
for (columnName, columnData) in df.items():
    na_count = columnData.isna().sum()
    unique_count = columnData.unique()
    print(f'{columnName}\'s data type: {columnData.dtypes}')
    print(f'N/A values in {columnName}: {na_count}')
    print(f'{columnName} values: {unique_count}\n')

processor_brand's data type: object
N/A values in processor_brand: 0
processor_brand values: ['AMD' 'Intel' 'M1' 'MediaTek' 'Qualcomm']

processor_name's data type: object
N/A values in processor_name: 0
processor_name values: ['A6-9225 Processor' 'APU Dual' 'Athlon Dual' 'Core i3' 'Core i5'
 'Celeron Dual' 'Ryzen' 'Ryzen 5' 'Core' 'Core i7' 'Core i9' 'Core m3'
 'Dual Core' 'Ever Screenpad' 'GeForce GTX' 'GeForce RTX' 'GEFORCE RTX'
 'Hexa Core' 'M1' 'Genuine Windows' 'Pentium Quad' 'Pentium Silver'
 'Ryzen 3' 'MediaTek Kompanio' 'Quad' 'Ryzen 7' 'Ryzen 9' 'Snapdragon 7c']

processor_generation's data type: object
N/A values in processor_generation: 0
processor_generation values: ['10th' 'Missing' '11th' '7th' '8th' '9th' '4th' '12th']

ram_gb's data type: object
N/A values in ram_gb: 0
ram_gb values: ['4 GB GB' '8 GB GB' '32 GB GB' '16 GB GB']

ram_type's data type: object
N/A values in ram_type: 0
ram_type values: ['DDR4' 'LPDDR4X' 'LPDDR4' 'DDR5' 'DDR3' 'LPDDR3']

ssd's data type: object
N/A values in ssd: 0
ssd values: ['0 GB' '128 GB' '256 GB' '32 GB' '512 GB' '1024 GB' '2048 GB' '3072 GB']

hdd's data type: object
N/A values in hdd: 0
hdd values: ['1024 GB' '512 GB' '0 GB' '2048 GB']

os's data type: object
N/A values in os: 0
os values: ['Windows' 'DOS' 'Mac']

os_bit's data type: object
N/A values in os_bit: 0
os_bit values: ['64-bit' '32-bit']

graphic_card_gb's data type: int64
N/A values in graphic_card_gb: 0
graphic_card_gb values: [0 4 2 6 8]

weight's data type: object
N/A values in weight: 0
weight values: ['ThinNlight' 'Casual' 'Gaming']

display_size's data type: object
N/A values in display_size: 0
display_size values: ['Missing' '14' '15.6' '14.96' '15' '14.1' '12.2' '13.3' '17.3' '13' '16'
 '14.9' '16.1' '14.2' '16.2' '13.4']

warranty's data type: int64
N/A values in warranty: 0
warranty values: [0 1 2 3]

touchscreen's data type: object
N/A values in touchscreen: 0
touchscreen values: ['No' 'Yes']

msoffice's data type: object
N/A values in msoffice: 0
msoffice values: ['No' 'Yes']

latest_price's data type: int64
N/A values in latest_price: 0
latest_price values: [ 24990  19590  19990  21490  20900  21896  26899  31990  34649  38999
  39999  69990  26990  22990  21990  58799  49999  54990  59990  93700
  72990  17490  35990  56490  65390  31999  32490  31799  29890  23990
  32955  46200  34429  37990  33980  39990  39490  38990  53990  46990
  37890  41990  45990  42490  32990  36990  38940  42990  49990  41490
  38490  44990  36490  38970  44900  44427  40200  40990  47999  71999
  41998  39998  48490  44376  43900  46690  43990  48500  48990  23490
  54238  51990  43970  41250  60790  45650  45490  38799  69267  51649
  47990  44890  50990  48900  41790  57999  45930  55490  32890  42190
  43690  43800  34990  38900  40890  39790  35590  33990  43400  40750
  43000  38000  49279  41500  36999  42900  41480  38680  40390  20490
  44490  41890  43590  44690  41390  44290  48999  46390  18990  17990
  26470  27990  29999  25990  16990  99990 119990  94190 106167  68090
 139990  55990 102551 100190  52990  91999  76012  49490 102990  86867
  76990  62990  81998 136590  59490  49800  61999  67990  57990  62300
  61990  63990  65990  71990  89990  71890  64990  55999  73490  74490
  58340  82990  64190  70090  60999  97990  66999  60990  59999  79990
  69490  89390  74990  66490  89702  70990  58990  57500  56541  61290
  84990  72500  87990  68990  77990 105990 111890  71090  53400  74500
 114990 159990 172090 147000 106490  62890 111999  70798  99500  62998
  88990 113590  73990  86990  61000  70799  53690  53190  58999  82000
  89998  69899  76300  72900  73519 126000 171998 114999 109999 129999
 149990  71290  79500  70980  94000  85990  78900 132790  65556  70190
  79590  52790  86999  78000  73063 100990  75990  84086 179990  84500
  74190 155411 125394  52490  56990  58090  61597  81990  61249  83990
 291190 145990  46790  44599  72964  48790  56491  62490  60190  54490
  55790  69900  74590  77900  67490  74999  68900  71695  62317 207290
  93190  94990 104000  90190  88488 109990 239759  78990 121890  92000
 162990 135300 174527 162299 109190  99999 104990 244801  86000 162399
 119599 211753 110999  66990 134990  98990 144690 194990 124990 122410
 154990 122990 224990 279990 121990 116990 151098 129990 149999 171990
  93955 234990 128500 120980 157249 229900 131500 165990 167990 165000
 136990 233990  93990 116941  82500  98912  92990 169990 192990 299990
 269990 265998 441990  29990 109590 146490  61745 209690 175190 199990
  75500 345390 214790 269290  95990 112990 132990 125990 103990 101990
 131990 128990 184990 225990 243990 309990 116640  13990  58100  30990
  36000  30780  77890  33690  40590  34500  43490  42090  37390  52632
  32917  41999  22490  44390  49970  47490  67500  62450  98020  49890
  73999  76190  74798  68100  55090  91990  84208  53490  76498  98920
  52380  52500  49590  75999  80990  59900  54590  51890  57900  81978
  68500  80000  75100 106990  81490  84988  90990  72400 111990 109000
  78988  73138  89570  73400  84190 130990  77988  76000 111000  84970
  80490 135990 146990 141990 142990 130500 138990 144990  57490]

old_price's data type: int64
N/A values in old_price: 0
old_price values: [ 32790  21325  27990  33490  22825      0  27668  36990  41990  42705
  43999  28990  25990  77990  59000  89000  99999 139000  23490  42990
  64923  76436  38999  39288  36999  33990  26990  49990  57990  46990
  50085  43312  51999  63510  52999  54999  52990  51990  60890  54510
  58990  61590  59654  49999  40614  75490  48200  55490  59999  56776
  68658  55448  57670  57290  51544  59239  53790  56590  51000  53900
  56800  54723  27000  72246  47990  60090  45892  49800  45376  57095
  48900  49821  50250  44990  58493  29990  50990  57330  49590  55999
  67990  62990  62190  60908  50294  50196  69267  55990  79690  46390
  46602  52900  78307  55202  49826  60046  63790  47916  51165  56999
  51748  50000  54784  85000  58229  65853  50693  44780  54517  48933
  48990  55506  55890  40990  55534  45990  45514  47264  46138  43296
  42787  39990  49000  30990  43090  46629  51493  45000  55351  43990
  54992  24990  54782  60371  57479  43126  60000  59990  59781  60122
  56743  57863  51976  57858  45810  59101  22990  21990  31532  37400
  40490  24840  34890 149999  89999 124900 124999 120990  69500 155720
  63179  90000  62290 104999  75390 139890 104000 106000  99000  71578
  82799 151133  65546  66990  68999  70171  74390  78294  81990 101390
  69999  84890  88990  97890  82990  78109  75999 115990  74990  64290
 105990 106990 129990  83990  89990  94201  92549  90990  66050 110990
  85359  74839  89849  80990 104990  85391  89395  64990 114749  76990
 115167  79890  79445  81684 103102  77327  89790  75023  92552 109353
  86990 151557  93690 104890  85990  86720  97946  61990 120708  73774
  66470 112608  80900 125890  69736 159180  80366 140990  95990  80711
 116990  76143 154446  88037  98990  87168  78990 115729  68859 174900
 179900  57240  65438  93565 138366 113290  77487  65000  84690 146194
 101090  84990 119999  77996  87999  70990  99203  98200 122803  75800
  90605 120000 130000  68000 122990  76915  89564  75879  69990  65999
  86000 101525  73899 117587  79999  74900  92600  88400 152042 237890
 138166  94600 117490  88600 155436 169990  95136  99433 107786  76094
  98000  94890  93489 141990  80000  92000  84900 172990  79990  90783
 106082 109000 113000  83458 101990 149990 194900 107990 126990 105000
  83417 121608 146680  70286  62511  72990  82999  62594  62549  68990
  68900 330990 201990  68270  50190  73199  54786  74833  64999  86199
  86690  60078  80284  87717  87320  99290  74066 109990  88519  82300
  82600  75500  78999  75732 235990  88532 153490  96990 118890 118776
 109696 114751 128665 107262  96995 134990  99240 139104  99990 117990
 113019 192977 135553 178999 119442 102500 123990 206997 195000 214760
 102987 146990 164990 136990 173453 128990 162990 216368 156990 167890
 272990 313990 138399 132717 224490 179990 178464 197862 122300 324990
 104033 158990 220990 272000 175000 202990 148082 198825  83390 148158
 160134 157563 349890 160190  97990 130990 199999 179999 223890 376990
 326990 144990  34990  32990 139990 209990 223322  83557 377798 237937
 293080 124078  92900 122900 112900 149900 163900 142900 117900 110900
 137900 239900 132900 183900 259900 329900 227250  19999  36865  43000
  40000  40108  38990 110890  46055  49714  50586  53640  37990  50132
  44999  42999  51105  56771  50651  40957  50149  49613  36923  51574
  48294  26663  24845  59580  58194  58286  56573  70172  83890  59808
  60959  78290  89490  61740  76020 107690  61060  75049  73990  23390
  70419  89992  66161  65566  88840  67861  80996  78900  67931  56990
 101681  58500  62200  93461  58657 123090  68192  66396  90890  85290
  83085  66560  57331 131990 138490 123540 132990 137000 111890 103215
  76090  67551  73625 114000 125888 128000  99067 114690 112990 152490
 111529  72000 108590  86352 111108 145990 112671 109566 139999 186348
 181890 137990 142990 117290  93564 119990 119900 118898 183990 207990
 259990 187990 175990 188990 181990 170990 163739 166990 155990 194990
 189990 210990 350990  78400]

discount's data type: int64
N/A values in discount: 0
discount values: [23  8 28 25  0  2 13 17  9  6 15 24 38 40 32 27 16 12 14 11 31 34 20 26
 35 22 30 19 33  7 18 21 37  1  3  5 10 36  4 43 29 41 46 47 57 56 48 39]

star_rating's data type: float64
N/A values in star_rating: 0
star_rating values: [3.7 3.6 3.9 0.  4.2 2.3 3.8 3.1 3.5 4.5 4.  4.1 4.3 4.4 4.6 4.8 5.  3.3
 4.7 3.4 3.  2.  3.2 2.9 2.8 1.6 4.9 1.7 2.5 2.7]

ratings's data type: int64
N/A values in ratings: 0
ratings values: [   63  1894  1153  1657  1185   219     0    76     3    65     8    31
  3190  1946   259   425  1120   286    58     7 15279   311    47    37
  2080  1479    67   273  1267  1063    14  6352   284    44    33    10
   816   543     9  1221  1178   299    20   758   634     4    17    24
  1753   216  1084    19   106    42  1029    53    48    61    97   181
   529  5205  1090     1    70   632    71   990   158   681   130    30
     6   174    40    13   184  1296   571  2551    35   118   245  2058
   117    74    39    29    43   984   523  1605  4008  1869  1278   143
    28  2124   276   250  1917  4999  4203    15   527   103   324    69
    16    12  1146  1850   231   502  1096   313   265    38   818    25
   974    83   637   207   844    62   724    56   170    95   197  1180
   232   596    84   414  1336 10966  1881    23   204  4428    49   129
   365    79    68   116   206   300   108  3712   825  3470    85  1708
  1119   155    91   126    75   124  1597  3850     5   213    93    11
   262    45  1681  1625   282   383   677    46    26  1541    72    59
   337   138   199    32   814   125   714    21   739   145   545  1124
    98   474   195     2    22   512  1365   368   202   187   253   470
  1444  1114    78    73   715  3062   122    18  1188    27   157    52
   343   131    41   328   353   127   241   898   179   114   268   153
   377   120   484   399    77    57  1639   498   445    54   794  2038
   214   342   218   762   298  2582  6725   640   809  3227  1218   465
   102  4741  2736    36   208  2214  2886    34   137   163   267  7291
   409  3524  4623   939   649  4740   162   193   562    92   469  1978
  1049   196   172  2887    86   104    90   183   358    88   364   826
  1410   741   700   349   519  1480   271   861   165   698   144  1810
  1067   530   139   105   191   134   198   272   141   194]

reviews's data type: int64
N/A values in reviews: 0
reviews values: [  12  256  159  234  141   18    0   13    5    1    3  414  240   47
   67  196   19    6 1947   27    7  235  181   30  171  152 1014   39
    4   36  147   65  265  137   41   64    2  165   21  160  107   11
  561   96    9   92    8  108   59   29  126   56  297   17   34  305
   99   66  215  519  135   15  233   40  189  490   46   10   45  175
  216   26   93  116   35  113  170   91   16  103   25  148   23   54
  186 1185  241  109  569   14   20   24  412   95  505  242  228  378
   31  227   87  123  112   71   74  100   37   85   48  118   28  179
  106  325  127   51  128   53  230   49   83  313  104  272  629   70
  693  209   89  658  350   57  375   33   42  895   58  432  553   84
  532   80  188  134  476   52  203  144   69  151  145   22]

**Tidy up the data**

Text mining (extract numbers from every row in a specified column) and type changing.

In [101]:
df['processor_generation'] = df['processor_generation'].str.extract('(\d+)')
df['ram_gb'] = df['ram_gb'].str.extract('(\d+)')
df['ssd'] = df['ssd'].str.extract('(\d+)')
df['hdd'] = df['hdd'].str.extract('(\d+)')
df['os_bit'] = df['os_bit'].str.extract('(\d+)')

df['processor_generation'] = pd.to_numeric(df['processor_generation'])
df['ram_gb'] = pd.to_numeric(df['ram_gb'])
df['ssd'] = pd.to_numeric(df['ssd'])
df['hdd'] = pd.to_numeric(df['hdd'])
df['os_bit'] = pd.to_numeric(df['os_bit'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   processor_brand       896 non-null    object
 1   processor_name        896 non-null    object
 2   processor_generation  657 non-null    float64
 3   ram_gb                896 non-null    int64
 4   ram_type              896 non-null    object
 5   ssd                   896 non-null    int64
 6   hdd                   896 non-null    int64
 7   os                    896 non-null    object
 8   os_bit                896 non-null    int64
 9   graphic_card_gb       896 non-null    int64
 10  weight                896 non-null    object
 11  display_size          896 non-null    object
 12  warranty              896 non-null    int64
 13  touchscreen           896 non-null    object
 14  msoffice              896 non-null    object
 15  latest_price          896 non-null    int64
 16  old_price             896 non-null    int64
 17  discount              896 non-null    int64
 18  star_rating           896 non-null    float64
 19  ratings               896 non-null    int64
 20  reviews               896 non-null    int64
dtypes: float64(2), int64(11), object(8)
memory usage: 147.1+ KB

Missing value handling

In [102]:
df[df['processor_name'] == 'Ryzen']

,processor_brand,processor_name,processor_generation,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,...,display_size,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
19,AMD,Ryzen,10.0,4,DDR4,0,512,Windows,32,4,...,Missing,0,No,No,54990,89000,38,4.5,3190,414

In [103]:
df[df['processor_name'] == 'Core']

,processor_brand,processor_name,processor_generation,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,...,display_size,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
213,Intel,Core,NaN,4,DDR4,0,512,Windows,32,0,...,Missing,0,No,No,99990,149999,33,4.5,1336,186

Since there are only two uninformative processor name, both data are going to be dropped.

In [104]:
df = df.drop(df[df['processor_name'] == 'Ryzen'].index)
df = df.drop(df[df['processor_name'] == 'Core'].index)

#re-check
df[df['processor_name'] == 'Core']

Empty DataFrame
Columns: [processor_brand, processor_name, processor_generation, ram_gb, ram_type, ssd, hdd, os, os_bit, graphic_card_gb, weight, display_size, warranty, touchscreen, msoffice, latest_price, old_price, discount, star_rating, ratings, reviews]
Index: []

[0 rows x 21 columns]

In [105]:
df['processor_generation'] = df['processor_generation'].fillna(np.mean(df['processor_generation']))

In [106]:
df['display_size'] = df['display_size'].replace('Missing', np.NaN)
df['display_size'] = pd.to_numeric(df['display_size'])
df['display_size'] = df['display_size'].fillna(np.mean(df['display_size']))

In [107]:
for (columnName, columnData) in df.items():
    na_count = columnData.isna().sum()
    unique_count = columnData.unique()
    print(f'{columnName}\'s data type: {columnData.dtypes}')
    print(f'N/A values in {columnName}: {na_count}')
    print(f'{columnName} values: {unique_count}\n')

processor_brand's data type: object
N/A values in processor_brand: 0
processor_brand values: ['AMD' 'Intel' 'M1' 'MediaTek' 'Qualcomm']

processor_name's data type: object
N/A values in processor_name: 0
processor_name values: ['A6-9225 Processor' 'APU Dual' 'Athlon Dual' 'Core i3' 'Core i5'
 'Celeron Dual' 'Ryzen 5' 'Core i7' 'Core i9' 'Core m3' 'Dual Core'
 'Ever Screenpad' 'GeForce GTX' 'GeForce RTX' 'GEFORCE RTX' 'Hexa Core'
 'M1' 'Genuine Windows' 'Pentium Quad' 'Pentium Silver' 'Ryzen 3'
 'MediaTek Kompanio' 'Quad' 'Ryzen 7' 'Ryzen 9' 'Snapdragon 7c']

processor_generation's data type: float64
N/A values in processor_generation: 0
processor_generation values: [10.         10.33231707 11.          7.          8.          9.
  4.         12.        ]

ram_gb's data type: int64
N/A values in ram_gb: 0
ram_gb values: [ 4  8 32 16]

ram_type's data type: object
N/A values in ram_type: 0
ram_type values: ['DDR4' 'LPDDR4X' 'LPDDR4' 'DDR5' 'DDR3' 'LPDDR3']

ssd's data type: int64
N/A values in ssd: 0
ssd values: [   0  128  256   32  512 1024 2048 3072]

hdd's data type: int64
N/A values in hdd: 0
hdd values: [1024  512    0 2048]

os's data type: object
N/A values in os: 0
os values: ['Windows' 'DOS' 'Mac']

os_bit's data type: int64
N/A values in os_bit: 0
os_bit values: [64 32]

graphic_card_gb's data type: int64
N/A values in graphic_card_gb: 0
graphic_card_gb values: [0 4 2 6 8]

weight's data type: object
N/A values in weight: 0
weight values: ['ThinNlight' 'Casual' 'Gaming']

display_size's data type: float64
N/A values in display_size: 0
display_size values: [15.12202128 14.         15.6        14.96       15.         14.1
 12.2        13.3        17.3        13.         16.         14.9
 16.1        14.2        16.2        13.4       ]

warranty's data type: int64
N/A values in warranty: 0
warranty values: [0 1 2 3]

touchscreen's data type: object
N/A values in touchscreen: 0
touchscreen values: ['No' 'Yes']

msoffice's data type: object
N/A values in msoffice: 0
msoffice values: ['No' 'Yes']

latest_price's data type: int64
N/A values in latest_price: 0
latest_price values: [ 24990  19590  19990  21490  20900  21896  26899  31990  34649  38999
  39999  69990  26990  22990  21990  58799  49999  59990  93700  72990
  17490  35990  56490  65390  31999  32490  31799  29890  23990  32955
  46200  34429  37990  33980  39990  39490  38990  53990  46990  37890
  41990  45990  42490  32990  36990  38940  42990  49990  41490  38490
  44990  36490  38970  44900  44427  40200  40990  47999  71999  41998
  39998  48490  44376  43900  46690  43990  48500  48990  23490  54238
  51990  43970  54990  41250  60790  45650  45490  38799  69267  51649
  47990  44890  50990  48900  41790  57999  45930  55490  32890  42190
  43690  43800  34990  38900  40890  39790  35590  33990  43400  40750
  43000  38000  49279  41500  36999  42900  41480  38680  40390  20490
  44490  41890  43590  44690  41390  44290  48999  46390  18990  17990
  26470  27990  29999  25990  16990 119990  94190 106167  68090 139990
  55990 102551 100190  52990  91999  76012  49490 102990  86867  76990
  62990  81998 136590  59490  49800  61999  67990  57990  62300  61990
  63990  65990  71990  89990  71890  64990  55999  73490  74490  58340
  82990  64190  70090  60999  97990  66999  60990  59999  79990  69490
  89390  74990  66490  89702  70990  58990  57500  56541  61290  84990
  72500  87990  68990  77990 105990 111890  71090  53400  74500 114990
 159990 172090 147000 106490  62890 111999  70798  99500  62998  88990
 113590  73990  86990  61000  99990  70799  53690  53190  58999  82000
  89998  69899  76300  72900  73519 126000 171998 114999 109999 129999
 149990  71290  79500  70980  94000  85990  78900 132790  65556  70190
  79590  52790  86999  78000  73063 100990  75990  84086 179990  84500
  74190 155411 125394  52490  56990  58090  61597  81990  61249  83990
 291190 145990  46790  44599  72964  48790  56491  62490  60190  54490
  55790  69900  74590  77900  67490  74999  68900  71695  62317 207290
  93190  94990 104000  90190  88488 109990 239759  78990 121890  92000
 162990 135300 174527 162299 109190  99999 104990 244801  86000 162399
 119599 211753 110999  66990 134990  98990 144690 194990 124990 122410
 154990 122990 224990 279990 121990 116990 151098 129990 149999 171990
  93955 234990 128500 120980 157249 229900 131500 165990 167990 165000
 136990 233990  93990 116941  82500  98912  92990 169990 192990 299990
 269990 265998 441990  29990 109590 146490  61745 209690 175190 199990
  75500 345390 214790 269290  95990 112990 132990 125990 103990 101990
 131990 128990 184990 225990 243990 309990 116640  13990  58100  30990
  36000  30780  77890  33690  40590  34500  43490  42090  37390  52632
  32917  41999  22490  44390  49970  47490  67500  62450  98020  49890
  73999  76190  74798  68100  55090  91990  84208  53490  76498  98920
  52380  52500  49590  75999  80990  59900  54590  51890  57900  81978
  68500  80000  75100 106990  81490  84988  90990  72400 111990 109000
  78988  73138  89570  73400  84190 130990  77988  76000 111000  84970
  80490 135990 146990 141990 142990 130500 138990 144990  57490]

old_price's data type: int64
N/A values in old_price: 0
old_price values: [ 32790  21325  27990  33490  22825      0  27668  36990  41990  42705
  43999  28990  25990  77990  59000  99999 139000  23490  42990  64923
  76436  38999  39288  36999  33990  26990  49990  57990  46990  50085
  43312  51999  63510  52999  54999  52990  51990  60890  54510  58990
  61590  59654  49999  40614  75490  48200  55490  59999  56776  68658
  55448  57670  57290  51544  59239  53790  56590  51000  53900  56800
  54723  27000  72246  47990  60090  45892  49800  45376  57095  48900
  49821  50250  44990  58493  29990  50990  57330  49590  55999  67990
  62990  62190  60908  50294  50196  69267  55990  79690  46390  46602
  52900  78307  55202  49826  60046  63790  47916  51165  56999  51748
  50000  54784  85000  58229  65853  50693  44780  54517  48933  48990
  55506  55890  40990  55534  45990  45514  47264  46138  43296  42787
  39990  49000  30990  43090  46629  51493  45000  55351  43990  54992
  24990  54782  60371  57479  43126  60000  59990  59781  60122  56743
  57863  51976  57858  45810  59101  22990  21990  31532  37400  40490
  24840  34890  89999 124900 124999 120990  69500 155720  63179  90000
  62290 104999  75390 139890 104000 106000  99000  71578  82799 151133
  65546  66990  68999  70171  74390  78294  81990 101390  69999  84890
  88990  97890  82990  78109  75999 115990  74990  64290 105990 106990
 129990  83990  89990  94201  92549  90990  66050 110990  85359  74839
  89849  80990 104990  85391  89395  64990 114749  76990 115167  79890
  79445  81684 103102  77327  89790  75023  92552 109353  86990 151557
  93690 104890  85990  86720  97946  61990 120708  73774  66470 112608
  80900 125890  69736 159180  80366 140990  95990  80711 116990  76143
 154446  88037  98990  87168  78990 115729  68859 174900 179900  57240
  65438  93565 138366 113290  77487  65000  84690 146194 101090  84990
 119999  77996  87999  70990  99203  98200 122803  75800  90605 120000
 130000  68000 122990  76915  89564  75879  69990  65999  86000  89000
 101525  73899 117587  79999  74900  92600  88400 152042 237890 138166
  94600 117490  88600 155436 169990  95136  99433 107786  76094  98000
  94890  93489 141990  80000  92000  84900 172990  79990  90783 106082
 109000 113000  83458 101990 149990 194900 107990 126990 105000  83417
 121608 146680  70286  62511  72990  82999  62594  62549  68990  68900
 330990 201990  68270  50190  73199  54786  74833  64999  86199  86690
  60078  80284  87717  87320  99290  74066 109990  88519  82300  82600
  75500  78999  75732 235990  88532 153490  96990 118890 118776 109696
 114751 128665 107262  96995 134990  99240 139104  99990 117990 113019
 192977 135553 178999 119442 102500 123990 206997 195000 214760 102987
 146990 164990 136990 173453 128990 162990 216368 156990 167890 272990
 313990 138399 132717 224490 179990 178464 197862 122300 324990 104033
 158990 149999 220990 272000 175000 202990 148082 198825  83390 148158
 160134 157563 349890 160190  97990 130990 199999 179999 223890 376990
 326990 144990  34990  32990 139990 209990 223322  83557 377798 237937
 293080 124078  92900 122900 112900 149900 163900 142900 117900 110900
 137900 239900 132900 183900 259900 329900 227250  19999  36865  43000
  40000  40108  38990 110890  46055  49714  50586  53640  37990  50132
  44999  42999  51105  56771  50651  40957  50149  49613  36923  51574
  48294  26663  24845  59580  58194  58286  56573  70172  83890  59808
  60959  78290  89490  61740  76020 107690  61060  75049  73990  23390
  70419  89992  66161  65566  88840  67861  80996  78900  67931  56990
 101681  58500  62200  93461  58657 123090  68192  66396  90890  85290
  83085  66560  57331 131990 138490 123540 132990 137000 111890 103215
  76090  67551  73625 114000 125888 128000  99067 114690 112990 152490
 111529  72000 108590  86352 111108 145990 112671 109566 139999 186348
 181890 137990 142990 117290  93564 119990 119900 118898 183990 207990
 259990 187990 175990 188990 181990 170990 163739 166990 155990 194990
 189990 210990 350990  78400]

discount's data type: int64
N/A values in discount: 0
discount values: [23  8 28 25  0  2 13 17  9  6 15 24 40 32 27 16 12 14 11 31 34 20 26 35
 22 30 19 33  7 18 21 37  1  3  5 10 36  4 43 29 38 41 46 47 57 56 48 39]

star_rating's data type: float64
N/A values in star_rating: 0
star_rating values: [3.7 3.6 3.9 0.  4.2 2.3 3.8 3.1 3.5 4.5 4.  4.1 4.3 4.4 4.6 4.8 5.  3.3
 4.7 3.4 3.  2.  3.2 2.9 2.8 1.6 4.9 1.7 2.5 2.7]

ratings's data type: int64
N/A values in ratings: 0
ratings values: [   63  1894  1153  1657  1185   219     0    76     3    65     8    31
  1946   259   425  1120   286    58     7 15279   311    47    37  2080
  1479    67   273  1267  1063    14  6352   284    44    33    10   816
   543     9  1221  1178   299    20   758   634     4    17    24  1753
   216  1084    19   106    42  1029    53    48    61    97   181   529
  5205  1090     1    70   632    71   990   158   681   130    30     6
   174    40    13   184  1296   571  2551    35   118   245  2058   117
    74    39    29    43   984   523  1605  4008  1869  1278   143    28
  2124   276   250  1917  4999  4203    15   527   103   324    69    16
    12  1146  1850   231   502  1096   313   265    38   818    25   974
    83   637   207   844    62   724    56   170    95   197  1180   232
   596    84   414 10966  1881    23   204  4428    49   129   365    79
    68   116   206   300   108  3712   825  3470    85  1708  1119   155
    91   126    75   124  1597  3850     5   213    93    11   262    45
  1681  1625   282   383   677    46    26  1541    72    59   337   138
   199    32   814   125   714    21   739   145   545  1124    98   474
   195     2    22   512  1365   368   202   187   253   470  1444  1114
    78    73   715  3062   122    18  1188    27   157    52   343   131
    41   328   353   127   241   898   179   114   268   153   377   120
   484   399    77    57  1639   498   445    54   794  2038   214   342
   218   762   298  2582  6725   640   809  3227  1218   465   102  4741
  2736    36   208  2214  2886    34   137   163   267  7291   409  3524
  4623   939   649  4740   162   193   562    92   469  1978  1049   196
   172  2887    86   104    90   183   358    88   364   826  1410   741
   700   349   519  1480   271   861   165   698   144  1810  1067   530
   139   105   191   134   198   272   141   194]

reviews's data type: int64
N/A values in reviews: 0
reviews values: [  12  256  159  234  141   18    0   13    5    1    3  240   47   67
  196   19    6 1947   27    7  235  181   30  171  152 1014   39    4
   36  147   65  265  137   41   64    2  165   21  160  107   11  561
   96    9   92    8  108   59   29  126   56  297   17   34  305   99
   66  215  519  135   15  233   40  189  490   46   10   45  175  216
   26   93  116   35  113  170   91   16  103   25  148   23   54 1185
  241  109  569   14   20   24  412   95  505  242  228  378   31  227
   87  123  112   71   74  100   37   85   48  118   28  179  106  325
  127   51  128   53  230   49   83  313  104  272  629   70  693  209
   89  658  350   57  375   33   42  895   58  432  553   84  532   80
  188  134  476   52  203  144   69  151  145   22]

Binary and label encoding:

In [108]:
from sklearn import preprocessing
label_encoding = preprocessing.LabelEncoder()

In [109]:
df['processor_brand'] = label_encoding.fit_transform(df['processor_brand'])

In [110]:
# #Replace GEFORCE RTX to GeForce RTX
df['processor_name'].replace('GEFORCE RTX', 'GeForce RTX', inplace = True)
df['processor_name'] = label_encoding.fit_transform(df['processor_name'])

In [111]:
df['ram_type'] = label_encoding.fit_transform(df['ram_type'])

In [112]:
df['os'] = label_encoding.fit_transform(df['os'])

In [113]:
df['weight'] = label_encoding.fit_transform(df['weight'])

In [114]:
df['touchscreen'] = label_encoding.fit_transform(df['touchscreen'])

In [115]:
df['msoffice'] = label_encoding.fit_transform(df['msoffice'])

In [116]:
df.head()

,processor_brand,processor_name,processor_generation,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,...,display_size,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,0,0,10.0,4,1,0,1024,2,64,0,...,15.122021,0,0,0,24990,32790,23,3.7,63,12
1,0,1,10.0,4,1,0,512,2,64,0,...,15.122021,0,0,0,19590,21325,8,3.6,1894,256
2,0,1,10.0,4,1,128,0,2,64,0,...,15.122021,0,0,0,19990,27990,28,3.7,1153,159
3,0,1,10.0,4,1,128,0,2,64,0,...,15.122021,0,0,0,21490,27990,23,3.7,1153,159
4,0,1,10.0,4,1,256,0,2,64,0,...,15.122021,0,0,0,24990,33490,25,3.7,1657,234

**Data modelling**

In [117]:
df_input = df.drop('latest_price', axis = 1)
df_output = df['latest_price']

In [118]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df_input, df_output, test_size = 0.2, random_state = 0)

In [119]:
from sklearn.neighbors import KNeighborsRegressor
KNN_regression = KNeighborsRegressor()
KNN_regression.fit(x_train, y_train)

KNeighborsRegressor()

In [120]:
y_predict=KNN_regression.predict(x_test)

In [121]:
from sklearn import metrics
from sklearn.metrics import r2_score
print("R2: ", r2_score(y_predict,y_test))
print("MSE: ", metrics.mean_squared_error(y_predict,y_test))
print("RMSE: ", metrics.mean_squared_error(y_predict,y_test) ** 0.5)
print("MAE: ", metrics.mean_absolute_error(y_predict,y_test))

R2:  0.8864479110731983
MSE:  245599791.8820112
RMSE:  15671.62377936668
MAE:  9024.201117318436